openapi: 3.0.3
info:
  title: Kubernetes Pod Server API
  version: 1.0.0
  description: API for managing Kubernetes Pods as servers.

servers:
  - url: /api/v1

paths:
  /tokens:
    post:
      tags:
        - token
      summary: Issue token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueTokenRequest'
      responses:
        '200':
          description: issued token.
          content:
            application/token:
              schema:
                $ref: '#/components/schemas/Token'
  /servers:
    get:
      tags:
        - server
      summary: List servers
      description: Get a list of all servers (Kubernetes Pods).
      responses:
        '200':
          description: A list of servers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
    post:
      tags:
        - server
      summary: Create server
      description: Create a new server (Kubernetes Pod).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerCreateRequest'
      responses:
        '201':
          description: Server created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'

  /servers/{serverId}:
    get:
      tags:
        - server
      summary: Get server details
      description: Get details of a specific server (Kubernetes Pod).
      parameters:
        - name: serverId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Server details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
        '404':
          description: Server not found.
    delete:
      tags:
        - server
      summary: Delete server
      description: Delete a specific server (Kubernetes Pod).
      parameters:
        - name: serverId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Server deleted.
        '404':
          description: Server not found.

  /images:
    get:
      tags:
        - image
      summary: List images
      description: Get a list of available images.
      responses:
        '200':
          description: A list of images.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'

components:
  schemas:
    Server:
      type: object
      required:
        - id
        - name
        - status
        - image
        - createdAt
      properties:
        id:
          type: string
          description: Server (Pod) ID
        name:
          type: string
          description: Server (Pod) name
        status:
          type: string
          description: Server (Pod) status
        image:
          type: string
          description: Image name
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
    ServerCreateRequest:
      type: object
      required:
        - name
        - image
      properties:
        name:
          type: string
          description: Server (Pod) name
        image:
          type: string
          description: Image name
    Image:
      type: object
      required:
        - name
        - tag
      properties:
        name:
          type: string
          description: Image name
        tag:
          type: string
          description: Image tag
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWT string
    IssueTokenRequest:
      type: object
      required:
        - namespace
      properties:
        namespace:
          type: string
          description: namespace
