openapi: 3.1.0
info:
  title: Authorization API
  version: 1.0.0
  description: トークン発行、検証 API を提供する

paths:
  /tokens:
    get:
      tags:
        - token
      summary: Verify token
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        "200":
          description: token is valid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Namespace"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - token
      summary: Issue token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IssueTokenRequest"
      responses:
        "200":
          description: issued token.
          content:
            application/token:
              schema:
                $ref: "#/components/schemas/Token"

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: unauthorized
    Namespace:
      type: object
      required:
        - namespace
      properties:
        namespace:
          type: string
          description: namespace
          example: default
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWT string
    IssueTokenRequest:
      type: object
      required:
        - namespace
      properties:
        namespace:
          type: string
          description: namespace
