// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"
)

// Deployment defines model for Deployment.
type Deployment struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Id Deployment ID
	Id string `json:"id"`

	// Image Image name
	Image string `json:"image"`

	// Name Deployment name
	Name string `json:"name"`

	// Status Deployment status
	Status string `json:"status"`
}

// DeploymentCreateRequest defines model for DeploymentCreateRequest.
type DeploymentCreateRequest struct {
	// Image Image name
	Image string `json:"image"`

	// Name Deployment name
	Name string `json:"name"`
}

// Image defines model for Image.
type Image struct {
	// Name Image name
	Name string `json:"name"`

	// Tag Image tag
	Tag string `json:"tag"`
}

// IssueTokenRequest defines model for IssueTokenRequest.
type IssueTokenRequest struct {
	// Namespace namespace
	Namespace string `json:"namespace"`
}

// Pod defines model for Pod.
type Pod struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Id Pod ID
	Id string `json:"id"`

	// Image Image name
	Image string `json:"image"`

	// Name Pod name
	Name string `json:"name"`

	// Status Pod status
	Status string `json:"status"`
}

// PodCreateRequest defines model for PodCreateRequest.
type PodCreateRequest struct {
	// Image Image name
	Image string `json:"image"`

	// Name Pod name
	Name string `json:"name"`
}

// Service defines model for Service.
type Service struct {
	// ClusterIP Cluster IP address
	ClusterIP string `json:"clusterIP"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Id Service ID
	Id string `json:"id"`

	// Name Service name
	Name string `json:"name"`

	// Ports List of service ports
	Ports []ServicePort `json:"ports"`

	// Type Service type (e.g., ClusterIP, NodePort, LoadBalancer)
	Type string `json:"type"`
}

// ServiceCreateRequest defines model for ServiceCreateRequest.
type ServiceCreateRequest struct {
	// Name Service name
	Name string `json:"name"`

	// Ports List of service ports
	Ports []ServicePort `json:"ports"`

	// Type Service type (e.g., ClusterIP, NodePort, LoadBalancer)
	Type string `json:"type"`
}

// ServicePort defines model for ServicePort.
type ServicePort struct {
	// Port Service port
	Port int `json:"port"`

	// Protocol Protocol (e.g., TCP, UDP)
	Protocol string `json:"protocol"`

	// TargetPort Target port
	TargetPort int `json:"targetPort"`
}

// Token defines model for Token.
type Token struct {
	// Token JWT string
	Token string `json:"token"`
}

// PostDeploymentsJSONRequestBody defines body for PostDeployments for application/json ContentType.
type PostDeploymentsJSONRequestBody = DeploymentCreateRequest

// PostPodsJSONRequestBody defines body for PostPods for application/json ContentType.
type PostPodsJSONRequestBody = PodCreateRequest

// PostServicesJSONRequestBody defines body for PostServices for application/json ContentType.
type PostServicesJSONRequestBody = ServiceCreateRequest

// PostTokensJSONRequestBody defines body for PostTokens for application/json ContentType.
type PostTokensJSONRequestBody = IssueTokenRequest
