apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-sql
  namespace: default
data:
  0-init.sql: |
    SET CHARACTER_SET_CLIENT = utf8mb4;
    SET CHARACTER_SET_CONNECTION = utf8mb4;

    CREATE DATABASE IF NOT EXISTS db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

  1-schema.sql: |
    SET CHARACTER_SET_CLIENT = utf8mb4;
    SET CHARACTER_SET_CONNECTION = utf8mb4;

    USE db;

    DROP TABLE IF EXISTS images;
    CREATE TABLE images
    (
      name  VARCHAR(64) NOT NULL COMMENT 'コンテナイメージ名',
      PRIMARY KEY (name)
    )
      COMMENT = 'コンテナイメージ';

    DROP TABLE IF EXISTS flavors;
    CREATE TABLE flavors
    (
      name  VARCHAR(64) NOT NULL COMMENT 'フレーバー名',
      PRIMARY KEY (name)
    )
      COMMENT = 'フレーバー';

  2-data.sql: |
    SET CHARACTER_SET_CLIENT = utf8mb4;
    SET CHARACTER_SET_CONNECTION = utf8mb4;

    USE db;

    INSERT INTO images (name) VALUES
    ('nginx:1.29.0'), ('nginx:otel'), ('nginx:1.28.0'),
    ('httpd:2.4.64'),
    ('busybox:1.37.0'), ('busybox:1.36'),
    ('hello-world:latest');

    INSERT INTO flavors (name) VALUES
    ('c1m1'), ('c1m2'), ('c1m4'), ('c1m8'),
    ('c2m1'), ('c2m2'), ('c2m4'), ('c2m8'),
    ('c3m1'), ('c3m2'), ('c3m4'), ('c3m8'),
    ('c4m1'), ('c4m2'), ('c4m4'), ('c4m8'),
    ('c6m1'), ('c6m2'), ('c6m4'), ('c6m8');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: db-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          envFrom:
            - configMapRef:
                name: db-env
      volumes:
        - name: db-sql
          configMap:
            name: db-sql
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
