apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: init
          image: grafana/grafana:12.0.2
          command:
            - mkdir -p /var/lib/grafana/plugins
            - grafana cli plugins install victoriametrics-metrics-datasource
          volumeMounts:
            - name: plugins
              mountPath: /var/lib/grafana
        - name: grafana
          image: grafana/grafana:12.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-ini
              mountPath: /etc/grafana
              readOnly: true
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning
              readOnly: true
            - name: plugins
              mountPath: /var/lib/grafana
          envFrom:
            - configMapRef:
                name: grafana-env
      volumes:
        - name: plugins
          emptyDir: {}
        - name: grafana-ini
          configMap:
            name: grafana-ini
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
            items:
              - key: datasources.yaml
                path: datasources/datasources.yaml
              - key: demo.yaml
                path: dashboards/demo.yaml
              - key: demo-dashboard.json
                path: dashboards/demo/demo-dashboard.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
