apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        # - name: init
        #   image: grafana/tempo:2.8.1
        #   entrypoint:
        #     - chown
        #     - "10001:10001"
        #     - /var/tempo
        - name: tempo
          image: grafana/tempo:2.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3200
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
          volumeMounts:
            - name: tempo-config
              mountPath: /etc
              readOnly: true
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tempo
  name: tempo
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: default
data:
  tempo.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: tempo:4317
          http:
            endpoint: tempo:4318
    processors:
    extensions:
      health_check: {}
    exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: http://prometheus:9090/api/v1/otlp
        tls:
          insecure: true
      debug:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp, debug]

        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/prometheus, debug]
