apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: default
data:
  scrape.yaml: |
    global:
      scrape_interval:     15s

    scrape_configs:
      - job_name: 'victoriametrics'
        static_configs:
          - targets: [ '${MY_POD_IP}:8428' ]
      - job_name: 'tempo'
        static_configs:
          - targets: [ 'tempo:3200' ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  labels:
    app: victoriametrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.122.0
          imagePullPolicy: IfNotPresent
          args:
            - -search.maxConcurrentRequests=16
            - -opentelemetry.usePrometheusNaming
            - -retentionPeriod=1d
            - -promscrape.config=/etc/victoriametrics/scrape.yaml
          ports:
            - containerPort: 8428
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: victoriametrics-config
              mountPath: /etc/victoriametrics
              readOnly: true
      volumes:
        - name: victoriametrics-config
          configMap:
            name: victoriametrics-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: victoriametrics
  name: victoriametrics
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: victoriametrics
  ports:
    - port: 8428
      targetPort: 8428
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: victoriametrics
  name: victoriametrics-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: victoriametrics
  ports:
    - port: 8428
      targetPort: 8428
