apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  labels:
    app: victoriametrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.122.0
          imagePullPolicy: IfNotPresent
          args:
            - -opentelemetry.usePrometheusNaming
          ports:
            - containerPort: 8428
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: victoriametrics
  name: victoriametrics
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: victoriametrics
  ports:
    - port: 8428
      targetPort: 8428
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: victoriametrics
  name: victoriametrics-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: victoriametrics
  ports:
    - port: 8429
      targetPort: 8428
