// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"
)

// Deployment defines model for Deployment.
type Deployment struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Deployment ID
	Id string `json:"id"`

	// Image Image name
	Image string `json:"image"`

	// Name Deployment name
	Name string `json:"name"`

	// Status Deployment status
	Status string `json:"status"`
}

// DeploymentCreateRequest defines model for DeploymentCreateRequest.
type DeploymentCreateRequest struct {
	// Image Image name
	Image string `json:"image"`

	// Name Deployment name
	Name string `json:"name"`

	// Port List of ports
	Port *[]int `json:"port,omitempty"`

	// Replicas Number of replicas
	Replicas *int `json:"replicas,omitempty"`
}

// Image defines model for Image.
type Image struct {
	// Name Image name
	Name string `json:"name"`

	// Tag Image tag
	Tag string `json:"tag"`
}

// Pod defines model for Pod.
type Pod struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Pod ID
	Id string `json:"id"`

	// Image Image name
	Image string `json:"image"`

	// Name Pod name
	Name string `json:"name"`

	// Status Pod status
	Status string `json:"status"`
}

// PodCreateRequest defines model for PodCreateRequest.
type PodCreateRequest struct {
	// Image Image name
	Image string `json:"image"`

	// Name Pod name
	Name string `json:"name"`
}

// Service defines model for Service.
type Service struct {
	// ClusterIP Cluster IP address
	ClusterIP string `json:"clusterIP"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Service ID
	Id string `json:"id"`

	// Name Service name
	Name string `json:"name"`

	// Ports List of service ports
	Ports []ServicePort `json:"ports"`

	// Type Service type (e.g., ClusterIP, NodePort, LoadBalancer)
	Type string `json:"type"`
}

// ServiceCreateRequest defines model for ServiceCreateRequest.
type ServiceCreateRequest struct {
	// Name Service name
	Name string `json:"name"`

	// Ports List of service ports
	Ports []ServicePort `json:"ports"`

	// Type Service type (e.g., ClusterIP, NodePort, LoadBalancer)
	Type string `json:"type"`
}

// ServicePort defines model for ServicePort.
type ServicePort struct {
	// Name Port name (optional)
	Name *string `json:"name,omitempty"`

	// Port Service port
	Port int `json:"port"`

	// Protocol Protocol (e.g., TCP, UDP)
	Protocol string `json:"protocol"`

	// TargetPort Target port
	TargetPort int `json:"targetPort"`
}

// Namespace defines model for Namespace.
type Namespace = string

// PostApiNamespaceDeploymentsJSONRequestBody defines body for PostApiNamespaceDeployments for application/json ContentType.
type PostApiNamespaceDeploymentsJSONRequestBody = DeploymentCreateRequest

// PostApiNamespacePodsJSONRequestBody defines body for PostApiNamespacePods for application/json ContentType.
type PostApiNamespacePodsJSONRequestBody = PodCreateRequest

// PostApiNamespaceServicesJSONRequestBody defines body for PostApiNamespaceServices for application/json ContentType.
type PostApiNamespaceServicesJSONRequestBody = ServiceCreateRequest
